### ISSUE TITLE
Webhook gets killed when result set is too large

### ISSUE THREAD

**Issue by morganatlooker** [looker/looker-slackbot#66]
Repro by saving [this explore](https://learn.looker.com/explore/ecommerce/orders?qid=mtGjRxLLXRMv9FyulxUqK2&origin_space=3779&toggle=vis) (Learn) as a look and schedule to slack. Hitting the "Send Test" button causes this message to appear in the logs: "Error: request entity too large"

```
2017-03-21T20:17:45.755434+00:00 heroku[router]: at=info method=POST path="/slack/post/dm/morgan" host=damp-dawn-62083.herokuapp.com request_id=6675c34a-6a1f-48a6-bc90-8a3cce37c1b1 fwd="34.196.135.9" dyno=web.1 connect=1ms service=21ms status=413 bytes=388 protocol=https
2017-03-21T20:17:45.740428+00:00 app[web.1]: Error: request entity too large
2017-03-21T20:17:45.740444+00:00 app[web.1]:     at emitOne (events.js:77:13)
2017-03-21T20:17:45.740448+00:00 app[web.1]:     at HTTPParser.parserOnBody (_http_common.js:121:22)
2017-03-21T20:17:45.740445+00:00 app[web.1]:     at IncomingMessage.emit (events.js:169:7)
2017-03-21T20:17:45.740449+00:00 app[web.1]: 
2017-03-21T20:17:45.740443+00:00 app[web.1]:     at IncomingMessage.onData (/app/node_modules/botkit/node_modules/body-parser/node_modules/raw-body/index.js:286:12)
2017-03-21T20:17:45.740446+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:153:18)
2017-03-21T20:17:45.740447+00:00 app[web.1]:     at IncomingMessage.Readable.push (_stream_readable.js:111:10)
```

**Comment by nitinpuri777** [comment]
@wilg  

It seems like this is the issue what Sourcegraph is facing [here](https://looker.zendesk.com/agent/tickets/81490), correct?    

Is there a short-term fix, like changing config settings, or modifying a part of the script to resolve this?  Since the client has asked about this a few times now (see ticket) it'd be great to either provide a quick solution for them or set appropriate expectations around timing for a fix.  

cc: @jirowiseman
